### ISSUE TITLE
Will it work with PhpStorm 2016.1?

### ISSUE THREAD

**Issue by RaeesBhatti** [k-jackson/jetbrains-hacklang#1]
I have PhpStorm 2016.1. Will it work with that?

**Comment by k-jackson** [comment]
Yes, though you'll have to configure the addon through IntelliJ, build the plugin, and import it into PhpStorm. I can post a build, if you're interested.

**Comment by RaeesBhatti** [comment]
Sure, a downloadable build would be great 👍

**Comment by k-jackson** [comment]
@raeesbhatti, you can download the jar at https://github.com/k-jackson/jetbrains-hacklang/releases/tag/v0.1.0

It needs lots of work, but let me know if you have any thoughts or suggestions.
