### ISSUE TITLE
Icon can't been seen in light themes

### ISSUE THREAD

**Issue by RaeesBhatti** [k-jackson/jetbrains-hacklang#2]
The `h` icon currently used for `.hh` files is plain white so, it can't be seen when used in light themes. Maybe we should add outline to it or use a different color?

![screen shot 2016-10-08 at 2 54 36 am](https://cloud.githubusercontent.com/assets/10067728/19207499/9c3ffb56-8d02-11e6-82da-e4d72e11c0e6.png)

**Comment by k-jackson** [comment]
The current icon is a (terrible) placeholder. I'll replace it with something more sensible.

**Comment by k-jackson** [comment]
Fixed in v0.1.1
